### ISSUE TITLE
AVA-Net Weights

### ISSUE THREAD

**Issue by sinagh72** [mansour2002/AVA-Net#1]
Can you share the trained AVA-Net Weights?

**Comment by mansour2002** [comment]
Thank you for your interest in our work and for considering the use of AVA-net in your study. To obtain the trained weights of AVA-net, please feel free to contact the corresponding author via email (xcy@uic.edu), and tell us about your study. We can provide you with the necessary information and resources.

**Comment by mansour2002** [comment]
Closing the issue.

**Comment by Adithya2406** [comment]
ran the model, could you let us know how to obtain the AVA ratio for a custom OCTA image?

**Comment by mansour2002** [comment]
> ran the model, could you let us know how to obtain the AVA ratio for a custom OCTA image?

By leveraging basic image processing methods in either Python with OpenCV or MATLAB, you can effectively obtain any ratio for a custom OCTA image.

**Comment by Adithya2406** [comment]
do you have any code or link for the same?
